title: Blog for Infinity
description: Welcome to Infinity's blog
theme: just-the-docs

url: https://infblog.github.io/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
